Models/Category/CategoryCreateModel.cs
using System.ComponentModel.DataAnnotations;

namespace MovieSite.Models;

public class CategoryCreateModel
{
    [Required(ErrorMessage = "Category Name is required")]
    [StringLength(100, ErrorMessage = "Name cannot be longer than 100 characters")]
    [Display(Name = "Category Name")]
    public string Name { get; set; } = null!;
}

Models/Category/CategoryEditModel.cs
using System.ComponentModel.DataAnnotations;

namespace MovieSite.Models;

public class CategoryEditModel
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Category Name is required")]
    [StringLength(100, ErrorMessage = "Name cannot be longer than 100 characters")]
    [Display(Name = "Category Name")]
    public string Name { get; set; } = null!;
}

Models/Category/CategoryGetModel.cs
namespace MovieSite.Models;

public class CategoryGetModel
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public int MovieCount { get; set; }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieSite.Data;
using MovieSite.Models;

namespace MovieSite.Controllers;

[Authorize(Roles = "Admin")]
public class CategoryController : Controller
{
    private readonly DataContext _context;

    public CategoryController(DataContext context)
    {
        _context = context;
    }

    public ActionResult Index()
    {
        var categories = _context.Categories.Select(i => new CategoryGetModel
        {
            Id = i.Id,
            Name = i.Name,
            MovieCount = i.Movies.Count()
        }).ToList();
        return View(categories);
    }


    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public ActionResult Create(CategoryCreateModel model)
    {
        if (ModelState.IsValid)
        {
            var category = new Category
            {
                Name = model.Name,
            };
            _context.Categories.Add(category);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(model);
    }

    public ActionResult Delete(int? id)
    {
        if (id == null)
        {
            return RedirectToAction("Index");
        }
        var category = _context.Categories.FirstOrDefault(i => i.Id == id);
        if (category != null)
        {
            return View(category);
        }
        return RedirectToAction("Index");
    }


    [HttpPost]
    public ActionResult DeleteConfirm(int? id)
    {
        if (id == null)
        {
            return RedirectToAction("Index");
        }
        var category = _context.Categories.FirstOrDefault(i => i.Id == id);
        if (category != null)
        {
            _context.Categories.Remove(category);
            _context.SaveChanges();
            TempData["Message"] = $"{category.Name} Category deleted successfully.";
            return RedirectToAction("Index");
        }
        return RedirectToAction("Index");
    }


    public ActionResult Edit(int id)
    {
        var category = _context.Categories.Select(i => new CategoryEditModel
        {
            Id = i.Id,
            Name = i.Name
        }).FirstOrDefault(i => i.Id == id);
        return View(category);
    }


    [HttpPost]
    public ActionResult Edit(int id, CategoryEditModel model)
    {
        if (id != model.Id)
        {
            return RedirectToAction("Index");
        }

        if (ModelState.IsValid)
        {
            var category = _context.Categories.FirstOrDefault(i => i.Id == id);
            if (category != null)
            {
                category.Name = model.Name;
                _context.SaveChanges();
                TempData["Message"] = $"{category.Name} Category updated successfully.";
                return RedirectToAction("Index");
            }
            return View(model);
        }
        return View(model);
    }

}

Controllers/MovieController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MovieSite.Data;
using MovieSite.Models;

namespace MovieSite.Controllers;


[Authorize(Roles = "Admin")]
public class MovieController : Controller
{
    private readonly DataContext _context;
    private readonly UserManager<AppUser> _userManager;
    public MovieController(DataContext context, UserManager<AppUser> userManager)
    {
        _userManager = userManager;
        _context = context;
    }


    public async Task<IActionResult> Index(string q, int page = 1, int pageSize = 10, int? category = null)
    {
        ViewBag.Categories = new SelectList(await _context.Categories.ToListAsync(), "Id", "Name");

        var query = _context.Movies.AsQueryable();

        if (!string.IsNullOrEmpty(q))
            query = query.Where(m => m.Title.ToLower().Contains(q.ToLower()));

        if (category.HasValue)
            query = query.Where(m => m.CategoryId == category.Value);

        int totalItems = await query.CountAsync();

        var movies = await query
            .OrderBy(m => m.Id)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .Select(m => new MovieGetModel
            {
                Id = m.Id,
                Title = m.Title,
                ReleaseDate = m.ReleaseDate,
                CategoryName = m.Category.Name,
                ImageUrl = m.ImageUrl
            })
            .ToListAsync();

        ViewData["CurrentPage"] = page;
        ViewData["TotalPages"] = (int)Math.Ceiling((double)totalItems / pageSize);
        ViewData["q"] = q;
        ViewData["category"] = category;

        return View(movies);
    }

    [AllowAnonymous]
    public async Task<IActionResult> Details(int id)
    {
        var movie = await _context.Movies
             .Include(m => m.Category)
             .Include(m => m.Comments)
             .ThenInclude(c => c.User)
             .FirstOrDefaultAsync(m => m.Id == id);

        if (movie == null)
        {
            return NotFound();
        }

        // Similar movies getirme örneği
        var similarMovies = await _context.Movies
            .Where(m => m.CategoryId == movie.CategoryId && m.Id != movie.Id)
            .OrderByDescending(m => m.Rating)
            .Take(4)
            .ToListAsync();

        ViewData["SimilarMovies"] = similarMovies;

        // Kullanıcının favori listesinde olan filmleri getir
        var userMovieIds = new List<int>();

        if (User.Identity!.IsAuthenticated)
        {
            var userIdStr = _userManager.GetUserId(User);
            if (int.TryParse(userIdStr, out int userId))
            {
                userMovieIds = await _context.MovieLists
                    .Where(ml => ml.UserId == userId)
                    .Select(ml => ml.MovieId)
                    .ToListAsync();
            }
        }

        ViewData["UserMovieIds"] = userMovieIds;

        return View(movie);
    }


    [AllowAnonymous]
    public IActionResult List(string categoryName, string q)
    {
        var movies = _context.Movies.Include(c => c.Category).AsQueryable();
        if (!string.IsNullOrEmpty(categoryName))
        {
            var category = _context.Categories.FirstOrDefault(c => c.Name == categoryName);
            if (category != null)
            {
                movies = movies.Where(m => m.CategoryId == category.Id);
            }
        }
        if (!string.IsNullOrEmpty(q))
        {
            movies = movies.Where(m => m.Title.ToLower().Contains(q.ToLower()));
            ViewData["q"] = q;
        }
        ViewBag.CategoryName = categoryName;

        return View(movies.ToList());
    }

    public ActionResult Delete(int id)
    {
        var movie = _context.Movies.FirstOrDefault(m => m.Id == id);
        if (movie == null)
        {
            return RedirectToAction("Index");
        }
        return View(movie);
    }

    [HttpPost]
    public ActionResult DeleteConfirm(int id)
    {
        var movie = _context.Movies.FirstOrDefault(m => m.Id == id);
        if (movie != null)
        {
            _context.Movies.Remove(movie);
            _context.SaveChanges();
            TempData["Message"] = $"{movie.Title} Movie deleted successfully.";
            return RedirectToAction("Index");
        }
        return RedirectToAction("Index");
    }

    public ActionResult Create()
    {
        ViewBag.Categories = new SelectList(_context.Categories.ToList(), "Id", "Name");
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(MovieCreateModel model)
    {
        if (model.Image == null || model.Image.Length == 0)
        {
            ModelState.AddModelError("Image", "Image is required.");
        }
        if (ModelState.IsValid)
        {
            var filename = Path.GetRandomFileName() + ".jpg";
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", filename);
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await model.Image!.CopyToAsync(stream);
            }
            var movie = new Movie
            {
                Title = model.Name,
                Description = model.Description,
                Rating = model.Rating,
                CategoryId = (int)model.CategoryId,
                ReleaseDate = model.ReleaseDate,
                ImageUrl = filename,
                TrailerUrl = model.TrailerUrl
            };
            _context.Movies.Add(movie);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        ViewBag.Categories = new SelectList(_context.Categories.ToList(), "Id", "Name", model.CategoryId);
        return View(model);
    }

    public ActionResult Edit(int id)
    {
        var movie = _context.Movies.Select(i => new MovieEditModel
        {
            Id = i.Id,
            Name = i.Title,
            Description = i.Description,
            ImageName = i.ImageUrl,
            ReleaseDate = i.ReleaseDate,
            Rating = i.Rating,
            TrailerUrl = i.TrailerUrl,
            CategoryId = i.CategoryId
        }).FirstOrDefault(i => i.Id == id);
        ViewBag.Categories = new SelectList(_context.Categories.ToList(), "Id", "Name", movie?.CategoryId);
        return View(movie);
    }


    [HttpPost]
    public async Task<ActionResult> Edit(int id, MovieEditModel model)
    {
        if (id != model.Id)
        {
            return RedirectToAction("Index");
        }

        if (ModelState.IsValid)
        {
            if (model.Image == null || model.Image.Length == 0)
            {
                ModelState.AddModelError("Image", "Image is required.");
            }
            var movie = _context.Movies.FirstOrDefault(i => i.Id == model.Id);
            if (movie != null)
            {
                if (model.Image != null)
                {
                    var fileName = Path.GetRandomFileName() + ".jpg";
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", fileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await model.Image!.CopyToAsync(stream);
                    }
                    movie.ImageUrl = fileName;
                }
                movie.Title = model.Name;
                movie.Description = model.Description;
                movie.Rating = model.Rating;
                movie.CategoryId = (int)model.CategoryId;
                movie.ReleaseDate = model.ReleaseDate;
                movie.TrailerUrl = model.TrailerUrl;
                _context.SaveChanges();
                TempData["Message"] = $"{movie.Title} Movie updated successfully.";
                return RedirectToAction("Index");
            }
        }
        ViewBag.Categories = new SelectList(_context.Categories.ToList(), "Id", "Name", model.CategoryId);
        return View(model);
    }

}

Views/Category/Create.cshtml
@model CategoryCreateModel

@{
    ViewData["Title"] = "Add Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="card shadow rounded-4 border-0">
            <div class="card-header bg-primary text-white py-3 d-flex justify-content-between align-items-center rounded-top-4">
                <h5 class="mb-0"><i class="fa-solid fa-folder-plus me-2"></i>Add Category</h5>
                <a asp-controller="Category" asp-action="Index" class="btn btn-light btn-sm text-primary fw-semibold">
                    <i class="fa-solid fa-list me-1"></i> Back to List
                </a>
            </div>
            <div class="card-body px-4 py-4">
                <form method="post" asp-controller="Category" asp-action="Create">
                    <div class="mb-3">
                        <label asp-for="Name" class="form-label fw-semibold">Category Name</label>
                        <input asp-for="Name" class="form-control" placeholder="Enter category name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="text-end">
                        <button type="submit" class="btn btn-success px-4">
                            <i class="fa-solid fa-check me-1"></i> Save Category
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Views/Category/Delete.cshtml
@using MovieSite.Data
@model Category

@{
    ViewData["Title"] = "Delete Category";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="card shadow-lg border-0 rounded-4">
            <div class="card-header bg-danger text-white py-3 rounded-top-4 d-flex justify-content-between align-items-center">
                <h5 class="mb-0">
                    <i class="fa-solid fa-trash-can me-2"></i>Delete Category
                </h5>
            </div>

            <div class="card-body text-center px-4 py-4">
                <p class="fs-5 mb-4">
                    Are you sure you want to delete the category: 
                    <span class="fw-bold text-danger">"@Model.Name"</span>?
                </p>

                <form asp-controller="Category" asp-action="DeleteConfirm" method="post" class="d-flex justify-content-center gap-3">
                    <input type="hidden" name="Id" value="@Model.Id" />

                    <button type="submit" class="btn btn-danger px-4">
                        <i class="fa-solid fa-trash me-1"></i> Delete
                    </button>
                    <a asp-controller="Category" asp-action="Index" class="btn btn-secondary px-4">
                        <i class="fa-solid fa-xmark me-1"></i> Cancel
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>

Views/Category/Edit.cshtml
@model CategoryEditModel

@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/_AdminLayout.cshtml"; // Use the admin layout
}

<div class="row">
    <div class="col">
        <div class="card shadow">
            <div class="card-header py-1 d-flex justify-content-between align-items-center">
                <h5 class="card-title">Update Category</h5>
                <a asp-action="Index" class="btn btn-sm btn-primary">
                    <i class="fa-solid fa-list"></i>
                </a>
            </div>
            <div class="card-body">
                <form method="post">
                    <input type="hidden" name="Id" value="@Model.Id" />
                    <div class="row mb-3">
                        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="Name" class="form-control">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-sm-10 offset-sm-2">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Views/Category/Index.cshtml
@model List<CategoryGetModel>

@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row justify-content-center">
    <div class="col-lg-10">
        <div class="card shadow rounded-4 border-0">
            <div
                class="card-header bg-primary text-white py-3 d-flex justify-content-between align-items-center rounded-top-4">
                <h5 class="mb-0"><i class="fa-solid fa-layer-group me-2"></i>Categories</h5>
                <a asp-controller="Category" asp-action="Create" class="btn btn-light btn-sm text-primary fw-semibold">
                    <i class="fa-solid fa-plus me-1"></i> Add Category
                </a>
            </div>
            <div class="card-body p-4">

                @if (!Model.Any())
                {
                    <div class="alert alert-warning text-center">
                        No categories found.
                    </div>
                }
                else
                {
                    <div class="table-responsive">
                        <table class="table table-hover align-middle mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th style="width: 70px;">#</th>
                                    <th>Category Name</th>
                                    <th class="text-end" style="width: 180px;">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var category in Model)
                                {
                                    <tr>
                                        <td>@category.Id</td>
                                        <td>@category.Name</td>
                                        <td class="text-end">
                                            <a asp-controller="Category" asp-action="Edit" asp-route-id="@category.Id"
                                                class="btn btn-outline-primary btn-sm me-1" title="Edit">
                                                <i class="fa-solid fa-pen-to-square"></i>
                                            </a>
                                            <a asp-controller="Movie" asp-route-category="@category.Id"
                                                class="btn btn-outline-secondary btn-sm me-1" title="View Movies">
                                                <i class="fa-solid fa-box-archive"></i>
                                            </a>
                                            @if (@category.MovieCount == 0)
                                            {
                                                <a asp-controller="Category" asp-action="Delete" asp-route-id="@category.Id"
                                                    class="btn btn-outline-danger btn-sm" title="Delete">
                                                    <i class="fa-solid fa-trash"></i>
                                                </a>
                                            }
                                            else
                                            {
                                                <button class="btn btn-outline-danger btn-sm" disabled title="Delete">
                                                    <i class="fa-solid fa-trash"></i>
                                                </button>
                                            }

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                }
            </div>
        </div>
    </div>
</div>